/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminNavBar: typeof import('./src/components/AdminNavBar.vue')['default']
    AdminProductCard: typeof import('./src/components/AdminProductCard.vue')['default']
    AdminProductDialog: typeof import('./src/components/AdminProductDialog.vue')['default']
    CommentCard: typeof import('./src/components/CommentCard.vue')['default']
    copy: typeof import('./src/components/ProductCard copy.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElInputNumer: typeof import('element-plus/es')['ElInputNumer']
    ElIntpu: typeof import('element-plus/es')['ElIntpu']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenueItem: typeof import('element-plus/es')['ElMenueItem']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRate: typeof import('element-plus/es')['ElRate']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    FarmerCard: typeof import('./src/components/FarmerCard.vue')['default']
    FarmerDialog: typeof import('./src/components/FarmerDialog.vue')['default']
    HomeCard: typeof import('./src/components/HomeCard.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    OrderCard: typeof import('./src/components/OrderCard.vue')['default']
    PaidDialog: typeof import('./src/components/PaidDialog.vue')['default']
    PayDialog: typeof import('./src/components/PayDialog.vue')['default']
    ProductCard: typeof import('./src/components/ProductCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchIcon: typeof import('./src/components/SearchIcon.vue')['default']
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
