server:
  port: 8081
spring:
  cloud:
    gateway:
      routes:
        - id: user # 路由规则id，自定义，唯一
          uri: lb://user-service # 路由的目标服务，lb代表负载均衡，会从注册中心拉取服务列表
          predicates: # 路由断言，判断当前请求是否符合当前规则，符合则路由到目标服务
            - Path=/user/** # 这里是以请求路径作为判断规则
        - id: product
          uri: lb://product-service
          predicates:
            - Path=/products/**
        - id: order
          uri: lb://order-service
          predicates:
            - Path=/order/**,/logistics/**
        - id: review
          uri: lb://review-service
          predicates:
            - Path=/review/**
        - id: upload
          uri: lb://upload-service
          predicates:
            - Path=/upload/**
ttag:
  auth:
    excludePaths:
      - /user/login
      - /user/register
      - /products/detail/**
      - /products/list/**
      - /products/vague
      - /review/product/**