version: "3.8"

services:
  ttag-gateway:
    build:
      context: ./ttag-gateway
      dockerfile: Dockerfile
    container_name: ttag-gateway
    ports:
      - "8081:8081"

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "8082:8082"

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    container_name: product-service
    ports:
      - "8083:8083"

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    container_name: order-service
    ports:
      - "8084:8084"

  review-service:
    build:
      context: ./review-service
      dockerfile: Dockerfile
    container_name: review-service
    ports:
      - "8085:8085"

  upload-service:
    build:
      context: ./upload-service
      dockerfile: Dockerfile
    container_name: upload-service
    ports:
      - "8086:8086"